http:
  port: "8081"
  
log:
  message: "Hi Welcome to VITech Talks , Here we are learning CI/CD Process with Jenkins"
  
deployment:
  app:
    runtime: "4.4.0"
  region: "us-east-2"
  workers: "1"
  workerType: "MICRO" 
  
  